development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: blogger_development
  pool: 5

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: blogger_test
  pool: 5